;; (DEFINE-CONFIGURATION WEB-BUFFER
;;   ((DEFAULT-MODES
;;     '(VI-NORMAL-MODE CERTIFICATE-EXCEPTION-MODE WEB-MODE BASE-MODE))))
;; (DEFINE-CONFIGURATION (BUFFER WEB-BUFFER)
;;   ((DEFAULT-MODES (APPEND '(VI-NORMAL-MODE) %SLOT-DEFAULT%))))
